In [1]:
import numpy as np

In [16]:
A=np.random.randint(0,20,[3,3])
B=np.random.randint(0,20,[3,3])
print(A,end='\n\n\n')
print(B)

[[ 6  6  1]
 [ 9  4  0]
 [14  6  8]]


[[ 2  4  2]
 [ 9  2 19]
 [13  2 10]]


In [24]:
np.dot(A,B)

array([[ 79,  38, 136],
       [ 54,  44,  94],
       [186,  84, 222]], dtype=int32)

In [25]:
np.matmul(A,B)#same as np.dot()

array([[ 79,  38, 136],
       [ 54,  44,  94],
       [186,  84, 222]], dtype=int32)

In [34]:
A1=np.linalg.inv(A)
print(A1,end='\n\n\n')
Z=A@A1
print(np.round(Z,10),end='\n\n\n')

[[-0.1322314   0.17355372  0.01652893]
 [ 0.29752066 -0.14049587 -0.03719008]
 [ 0.00826446 -0.19834711  0.12396694]]


[[ 1. -0.  0.]
 [-0.  1. -0.]
 [-0. -0.  1.]]




In [32]:
s=np.sum(A)
v=np.var(A)
print(s,end='\n\n')
print(v,end='\n')

54

15.777777777777779


In [38]:
mx=np.max(A)
mn=A.min()
print(mx,mn,sep='\n')

14
0


In [44]:
A5=np.where(A<5,5,A)
print(A5,end='\n\n\n')
Abool=np.where(A>5)
print(Abool)

[[ 6  6  5]
 [ 9  5  5]
 [14  6  8]]


(array([0, 0, 1, 2, 2, 2]), array([0, 1, 0, 0, 1, 2]))


In [56]:
print(np.any(A==0))

print(np.any(A==0,axis=0))
print(np.any(A==0,axis=1))

True
[False False  True]
[False  True False]


In [61]:
print(np.all(A<15))
print(np.allclose(Z,np.eye(3)))

True
True
