In [3]:
import numpy as np

In [4]:
a=np.arange(0,10,2)
print(a)

b=np.arange(1,11,3)
print(b)

[0 2 4 6 8]
[ 1  4  7 10]


In [13]:
x=np.linspace(0,90, 10)

print(x)
print(np.reshape(x,[2,5]))

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
[[ 0. 10. 20. 30. 40.]
 [50. 60. 70. 80. 90.]]


In [26]:
x0=np.zeros((2,2,2))#both tuple and lists can be given for dimensions
x1=np.ones([2,2,3])

print(x0,end='\n\n\n')
print(x1)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [16]:
arr=[1,5,2,7,3,5,7,12,4,1,7,11]
narr=np.array(arr)

print(arr)
print(narr)

[1, 5, 2, 7, 3, 5, 7, 12, 4, 1, 7, 11]
[ 1  5  2  7  3  5  7 12  4  1  7 11]


In [25]:
narr.shape

print(np.reshape(narr,[2,2,3]),end='\n\n\n')
print(np.reshape(narr,[3,4]))

[[[ 1  5  2]
  [ 7  3  5]]

 [[ 7 12  4]
  [ 1  7 11]]]


[[ 1  5  2  7]
 [ 3  5  7 12]
 [ 4  1  7 11]]


In [82]:
a=np.random.rand(3,3)
b=np.random.randint(5,500,[2,3])
c=np.random.randn(2,3)

print('a\n',a,end='\n\n\n')
print('b\n',b,end='\n\n\n')
print('c\n',c,end='\n\n\n')

print(np.concatenate([a,b,c], axis=0))

a
 [[0.96006224 0.35314211 0.90667972]
 [0.9693828  0.14949098 0.95647181]
 [0.93870519 0.27722297 0.4481452 ]]


b
 [[134 248 224]
 [190 153  55]]


c
 [[ 3.60932221 -0.50816026 -0.81491391]
 [ 1.42282805  0.7405293  -0.69925632]]


[[ 9.60062239e-01  3.53142105e-01  9.06679724e-01]
 [ 9.69382800e-01  1.49490976e-01  9.56471814e-01]
 [ 9.38705190e-01  2.77222967e-01  4.48145204e-01]
 [ 1.34000000e+02  2.48000000e+02  2.24000000e+02]
 [ 1.90000000e+02  1.53000000e+02  5.50000000e+01]
 [ 3.60932221e+00 -5.08160259e-01 -8.14913910e-01]
 [ 1.42282805e+00  7.40529299e-01 -6.99256323e-01]]


In [89]:
print('transpose of matrix b is\n',b.T,end='\n\n')#transpose
print('matrix AxB is\n',b*c,end='\n\n')

if np.all(b.T==np.transpose(b)):
    print("Note:\'T attribute is the same as numpy transpose function\'")

transpose of matrix b is
 [[134 190]
 [248 153]
 [224  55]]

matrix AxB is
 [[ 483.64917663 -126.02374433 -182.54071585]
 [ 270.33732998  113.30098272  -38.45909778]]

Note:'T attribute is the same as numpy transpose function'


In [91]:
ba=b-100
bd=b/10 
print(ba,bd,sep='\n\n')

[[ 34 148 124]
 [ 90  53 -45]]

[[13.4 24.8 22.4]
 [19.  15.3  5.5]]
