In [1]:
import numpy as np

In [4]:
a=np.arange(0,10,2)
print(a)

b=np.arange(1,11,3)
print(b)

[0 2 4 6 8]
[ 1  4  7 10]


In [13]:
x=np.linspace(0,90, 10)
print(x)
print(np.reshape(x,[2,5]))

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
[[ 0. 10. 20. 30. 40.]
 [50. 60. 70. 80. 90.]]
